"""add colum column

Revision ID: 416ff675a729
Revises: e646bf57411d
Create Date: 2024-02-14 18:53:08.997433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "416ff675a729"
down_revision: Union[str, None] = "e646bf57411d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User_Table",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("time", sa.TIMESTAMP(), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),

        sa.Column("email", sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_User_Table_email"), "User_Table", ["email"], unique=True )

    op.create_table(
        "News_Letter_Table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True,),
        sa.Column("email", sa.String(), server_default="", nullable=True),
        sa.Column("subscription_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_subscription", sa.Boolean(), nullable=False),

        sa.ForeignKeyConstraint(["user_id"], ["User_Table.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )

    op.create_table(
        "Role_Table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False,),
        sa.Column("email", sa.String(), server_default="", nullable=True),
        sa.Column("role", sa.String(length=5), server_default="user", nullable=False),

        sa.ForeignKeyConstraint(["user_id"], ["User_Table.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Role_Table")
    op.drop_table("News_Letter_Table")
    op.drop_index(op.f("ix_User_Table_email"), table_name="User_Table")
    op.drop_table("User_Table")
    # ### end Alembic commands ###
