"""add comment table

Revision ID: 21f2ca6bc91e
Revises: 416ff675a729
Create Date: 2024-02-24 21:36:06.788883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "21f2ca6bc91e"
down_revision: Union[str, None] = "416ff675a729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Comment_Table",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("comment_date", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("content", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User_Table.id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column(
        "News_Letter_Table", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "News_Letter_Table",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "Role_Table",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.create_unique_constraint(None, "User_Table", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User_Table", type_="unique")
    op.alter_column(
        "Role_Table",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "News_Letter_Table",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "News_Letter_Table", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_table("Comment_Table")
    # ### end Alembic commands ###
