"""Comment_Table unique=False

Revision ID: 7fa1b101cac3
Revises: 21f2ca6bc91e
Create Date: 2024-02-24 22:33:41.143204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fa1b101cac3"
down_revision: Union[str, None] = "21f2ca6bc91e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Comment_Table_user_id_key", "Comment_Table", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "Comment_Table_user_id_key", "Comment_Table", ["user_id"]
    )
    # ### end Alembic commands ###
